name: Swaparoo
version: '1.0.1'
main: au.com.addstar.swaparoo.SwaparooPlugin
api-version: '1.19'
description: Tool for swapping/using keys and gems
softdepend: [Vault, PlaceholderAPI]
commands:
  swaparoo:
    description: "Base command for Swaparoo"
    usage: "/swaparoo"
    permission: swaparoo.admin
  stargems:
    description: "Check your StarGem balance"
    usage: "/stargems"
    permission: swaparoo.command.balance
    aliases: [gems]
  buyconfirm:
    description: "Confirm a purchase with StarGems"
    usage: "/buyconfirm"
    permission: swaparoo.command.confirm
permissions:
  swaparoo.admin:
    description: "Allows access to Swaparoo commands"
    default: op
    children:
      swaparoo.command.reload: true
      swaparoo.command.debug: true
      swaparoo.command.keys: true
      swaparoo.command.stargems: true
